name: Update Repo
on:
  repository_dispatch:
    types: [Matrix]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: matrix
        
        
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython
          
      - name: Run Repo Build
        run: |
          ./tools/create_repository.py \
          https://github.com/Space2Walker/script.module.metahandler.git#matrix \
          https://github.com/Space2Walker/plugin.program.dnsleaktest.git#matrix \
          https://github.com/Space2Walker/plugin.video.chaturbate.git#matrix
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          branch: matrix
          commit_message: Automated Repo Update
