name: Update Repo
on:
  repository_dispatch:
    types: [metahandler]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gitpython

      - name: Run Repo Build
        run: |
          ./tools/create_repository.py \
          https://github.com/Space2Walker/script.module.metahandler.git \
          ./plugin.program.dnsleaktest \
          ./plugin.video.chaturbate \
          ./plugin.video.wrestling24 \
          ./plugin.video.xvideos \

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Automated Repo Update (Metahandler)
